# Makefile for empty SVM-struct API, 03.10.06

#Call 'make' using the following line to make CYGWIN produce stand-alone Windows executables
#		make 'SFLAGS=-mno-cygwin'

#You have to specify the TEST_PATH and MODEL_PATH to "make run"(needs output_trim.py, trim_ans_54.csv in directory
TRAIN_PATH = /tmp3/mlds_hw1/MLDS_HW1_RELEASE_v1/fbank/train_v.ark
TEST_PATH = /tmp3/mlds_hw1/MLDS_HW1_RELEASE_v1/fbank/test_v.ark
MODEL_PATH = victoriaSecret_100

#Use the following to compile under unix or cygwin
CC = gcc
LD = gcc

CFLAGS =   $(SFLAGS) -O3 -fomit-frame-pointer -ffast-math -Wall 
LDFLAGS =  $(SFLAGS) -O3 -lm -Wall
#CFLAGS =  $(SFLAGS) -pg -Wall
#LDFLAGS = $(SFLAGS) -pg -lm -Wall 

all: svm_empty_learn svm_empty_classify

run: 
	wget http://cmlab.csie.ntu.edu.tw/~eric11220/test_v.ark
	./svm_empty_classify $(TEST_PATH) $(MODEL_PATH) predict_results
	python map2phone.py middle.out predict_results $(TEST_PATH)
	python label2seq.py middle.out output.kaggle
	rm middle.out

run_all:
	wget http://cmlab.csie.ntu.edu.tw/~eric11220/trainfile.ark
	./svm_empty_learn $(TRAIN_PATH) $(MODEL_PATH)
	./svm_empty_classify $(TEST_PATH) $(MODEL_PATH) predict_results
	wget http://cmlab.csie.ntu.edu.tw/~eric11220/test_v.ark
	python map2phone.py middle.out predict_results $(TEST_PATH)
	python label2seq.py middle.out output.kaggle
	rm middel.out

.PHONY: clean
clean: svm_light_clean svm_struct_clean
	rm -f *.o *.tcov *.d core gmon.out *.stackdump 

#-----------------------#
#----   SVM-light   ----#
#-----------------------#
svm_light_hideo_noexe: 
	cd svm_light; make svm_learn_hideo_noexe

svm_light_clean: 
	cd svm_light; make clean

#----------------------#
#----  STRUCT SVM  ----#
#----------------------#

svm_struct_noexe: 
	cd svm_struct; make svm_struct_noexe

svm_struct_clean: 
	cd svm_struct; make clean


#-------------------------#
#----  SVM empty API  ----#
#-------------------------#

svm_empty_classify: svm_light_hideo_noexe svm_struct_noexe svm_struct_api.o svm_struct/svm_struct_classify.o svm_struct/svm_struct_common.o svm_struct/svm_struct_main.o 
	$(LD) $(LDFLAGS) svm_struct_api.o svm_struct/svm_struct_classify.o svm_light/svm_common.o svm_struct/svm_struct_common.o -o svm_empty_classify $(LIBS)

svm_empty_learn: svm_light_hideo_noexe svm_struct_noexe svm_struct_api.o svm_struct_learn_custom.o svm_struct/svm_struct_learn.o svm_struct/svm_struct_common.o svm_struct/svm_struct_main.o
	$(LD) $(LDFLAGS) svm_struct/svm_struct_learn.o svm_struct_learn_custom.o svm_struct_api.o svm_light/svm_hideo.o svm_light/svm_learn.o svm_light/svm_common.o svm_struct/svm_struct_common.o svm_struct/svm_struct_main.o -o svm_empty_learn $(LIBS)


svm_struct_api.o: svm_struct_api.c svm_struct_api.h svm_struct_api_types.h svm_struct/svm_struct_common.h
	$(CC) -c $(CFLAGS) svm_struct_api.c -o svm_struct_api.o

svm_struct_learn_custom.o: svm_struct_learn_custom.c svm_struct_api.h svm_light/svm_common.h svm_struct_api_types.h svm_struct/svm_struct_common.h
	$(CC) -c $(CFLAGS) svm_struct_learn_custom.c -o svm_struct_learn_custom.o

